[tool.mypy]
mypy_path = "stubs:third_party/pybind11"
strict_optional = true
warn_return_any = true
warn_no_return = true
# TODO warn_unused_ignores = true
warn_redundant_casts = true
warn_incomplete_stub = true
# TODO disallow_untyped_calls = true
check_untyped_defs = true
disallow_any_generics = true
no_implicit_optional = true
# TODO disallow_incomplete_defs = true
# TODO disallow_subclassing_any = true
disallow_untyped_decorators = true
warn_unused_configs = true
exclude = [
  '\.git',
  '__pycache__',
  '^build',
  '^third_party',
  '_pb2.py',
  '\.cache',
  '\.eggs',
  '\.setuptools-cmake-build',
]

# mypy per-module options:

[[tool.mypy.overrides]]
module = "onnx.*"
disallow_untyped_defs = true

[[tool.mypy.overrides]]
module = "tools.*"
warn_return_any = false

[[tool.mypy.overrides]]
module = "setup"
ignore_errors = true
