trigger:
- main

jobs:
- job: 'Test'
  pool:
    vmImage: ubuntu-latest
  strategy:
    matrix:
      py311-ml-debug:
        python.version: '3.11'
        onnx_ml: true
        onnx_debug: true
        documentation: false
      py310-ml:
        python.version: '3.10'
        onnx_ml: true
        onnx_debug: false
        documentation: false
      py39:
        python.version: '3.9'
        onnx_ml: false
        onnx_debug: true
        documentation: false
      py38:
        python.version: '3.8'
        onnx_ml: false
        onnx_debug: false
        documentation: true
      py37-ml:
        python.version: '3.7'
        onnx_ml: true
        onnx_debug: false
        documentation: false
    maxParallel: 6

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      addToPath: true

  - script: |
      sudo apt-get install libprotobuf-dev protobuf-compiler
      git submodule update --init --recursive
    displayName: 'Set up the ONNX environment and build flags'
  - script: |
      export DEBUG=1
    condition: eq(variables['onnx_debug'], true)
    displayName: 'Set DEBUG'
  - script: |
      export ONNX_ML=1
    condition: eq(variables['onnx_ml'], true)
    displayName: 'Set ONNX_ML'
  - script: |
      pip install nox
    displayName: 'Install nox'

  - script: |
      nox --forcecolor --no-venv -- -v --cov=onnx --cov-report=xml --cov-append --cov-branch
    displayName: 'Run ONNX tests'

  - script: |
      pip install -r docs/docsgen/source/requirements.txt
      cd docs/docsgen && make text -j auto
    condition: eq(variables['documentation'], true)
    displayName: Test documentation
    continueOnError: true  # the documentation generates errors due to operators documentation

  - script: |
      curl -Os https://uploader.codecov.io/latest/linux/codecov

      chmod +x codecov
      ./codecov
    displayName: 'Upload coverage to codecov'
