trigger:
- main

jobs:
- job: 'Test'
  pool:
    vmImage: macOS-latest
  strategy:
    matrix:
      py39:
        python.version: '3.9'
        onnx_ml: false
        onnx_debug: false
        onnx_lite: false
      py38:
        python.version: '3.8'
        onnx_ml: false
        onnx_debug: false
        onnx_lite: true
      py38-ml:
        python.version: '3.8'
        onnx_ml: true
        onnx_debug: false
        onnx_lite: true
      py38-ml-debug:
        python.version: '3.8'
        onnx_ml: true
        onnx_debug: true
        onnx_lite: false
      py37-ml-debug:
        python.version: '3.7'
        onnx_ml: true
        onnx_debug: true
        onnx_lite: false
    maxParallel: 6

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'

  - script: |
      export NUM_CORES=`sysctl -n hw.logicalcpu`
      if [ '$(onnx_debug)' == '1' ]; then
        source workflow_scripts/protobuf/build_protobuf_unix.sh $NUM_CORES $(pwd)/protobuf/protobuf_install Debug
      else
        source workflow_scripts/protobuf/build_protobuf_unix.sh $NUM_CORES $(pwd)/protobuf/protobuf_install
      fi
    displayName: 'Install Protobuf from source'
  - script: |
      git submodule update --init --recursive
    displayName: 'Load all submodules'

  - script: |
      export DEBUG=1
    condition: eq(variables['onnx_debug'], true)
    displayName: 'Set DEBUG'
  - script: |
      export ONNX_ML=1
    condition: eq(variables['onnx_ml'], true)
    displayName: 'Set ONNX_ML'
  - script: |
      export CMAKE_ARGS="-DONNX_WERROR=ON -DONNX_USE_LITE_PROTO=ON"
    condition: eq(variables['onnx_lite'], true)
    displayName: 'Add ONNX_USE_LITE_PROTO to CMAKE_ARGS'

  - script: |
      pip install nox
    displayName: 'Install nox'

  - script: |
      nox --forcecolor --no-venv -- -v --cov=onnx --cov-report=xml --cov-append --cov-branch
    displayName: 'Run ONNX tests'

  - script: |
      curl -Os https://uploader.codecov.io/latest/macos/codecov

      chmod +x codecov
      ./codecov -t ${CODECOV_TOKEN}
    displayName: 'Upload coverage to codecov'
    continueOnError: true
